# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 13:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_created=True, verbose_name='Timestamp')),
                ('name', models.CharField(max_length=128, verbose_name='Result name')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Data')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Result')),
                ('ip', models.GenericIPAddressField(verbose_name='Client IP')),
            ],
        ),
    ]
